import Foundation
import SpliceCore
import SwiftSyntax

/// The verdict for one edited file, per DESIGN.md section 7.2.
public enum ChangeClassification: Sendable {
    case noChange
    case hotPatch([PatchableDeclaration])
    case rebuildRequired(reason: String)
}

/// Compares two versions of a file and decides whether the difference is
/// body-only.
///
/// The rule is deliberately narrow: every declaration must still be there with
/// an identical signature, nothing outside the indexed declarations may differ,
/// and at least one body must have changed. Anything else is a rebuild. An
/// over-conservative false negative costs a rebuild; a false positive corrupts
/// a running process, so the asymmetry is the whole design (PRD.md FR-4).
public enum ChangeClassifier {
    public static func classify(baseline: String, current: String,
                                policy: ClassifierPolicy = .default) -> ChangeClassification {
        classify(before: DeclarationIndexer.index(source: baseline, policy: policy),
                 after: DeclarationIndexer.index(source: current, policy: policy))
    }

    /// For callers that already have the indexes and need something else from
    /// them, such as the imports the generator has to copy. Parsing the file a
    /// second time to read those was both wasted work and a place for the two
    /// parses to disagree about the policy.
    public static func classify(before: FileIndex, after: FileIndex) -> ChangeClassification {

        if before.residue != after.residue {
            return .rebuildRequired(reason: "something outside a replaceable declaration changed, such as a type's declaration, an import, or a stored property")
        }

        // A declaration that appeared or disappeared changes the module, not
        // just an implementation.
        let beforeKeys = Set(before.patchable.keys).union(before.unsupported.keys)
        let afterKeys = Set(after.patchable.keys).union(after.unsupported.keys)
        if beforeKeys != afterKeys {
            let added = afterKeys.subtracting(beforeKeys).sorted()
            let removed = beforeKeys.subtracting(afterKeys).sorted()
            var parts: [String] = []
            if !added.isEmpty { parts.append("added \(added.joined(separator: ", "))") }
            if !removed.isEmpty { parts.append("removed \(removed.joined(separator: ", "))") }
            return .rebuildRequired(reason: "the set of declarations changed: \(parts.joined(separator: "; "))")
        }

        for (identity, old) in before.unsupported {
            guard let new = after.unsupported[identity] else {
                return .rebuildRequired(reason: "\(identity) changed kind")
            }
            if old.fingerprint != new.fingerprint {
                return .rebuildRequired(reason: "\(identity): \(new.reason)")
            }
        }

        var changed: [PatchableDeclaration] = []
        for (identity, old) in before.patchable {
            guard let new = after.patchable[identity] else {
                return .rebuildRequired(reason: "\(identity) changed kind")
            }
            if old.signature != new.signature {
                return .rebuildRequired(reason: "\(identity): the signature changed, which is ABI-relevant")
            }
            if old.body != new.body {
                changed.append(new)
            }
        }

        if changed.isEmpty { return .noChange }
        return .hotPatch(changed.sorted { $0.identity < $1.identity })
    }
}

/// Emits the replacement source for a set of body-only changes.
///
/// The original declaration node is reused as the template, with only its name
/// and attributes rewritten. Reassembling a signature from parts would lose
/// something eventually --- an ownership modifier, a global actor, a where
/// clause --- and the failure would be silent. Copying the node cannot.
public enum ReplacementGenerator {
    public static func generate(module: String, generation: UInt64,
                                declarations: [PatchableDeclaration],
                                imports: [String] = []) throws -> String {
        var lines: [String] = [
            "// Generated by swift-splice for generation \(generation). Do not edit.",
            "",
            "@testable import \(module)",
        ]

        // The original file's imports, minus one that would duplicate the
        // module's own. Compared by module name: a `contains` test on the name
        // dropped `import FixtureKit` from a module called Fixture, and
        // `import CoreData` from one called Core, reintroducing the very
        // "cannot find type in scope" failure carrying imports exists to
        // prevent. Lines that are `#if` scaffolding pass through untouched.
        for statement in imports {
            guard statement.hasPrefix("import") || statement.contains(" import ") else {
                lines.append(statement)   // #if / #else / #endif
                continue
            }
            if DeclarationIndexer.moduleName(of: statement) == module { continue }
            lines.append(statement)
        }
        lines.append("")

        // One extension per context keeps the output readable when several
        // declarations on the same type change together.
        let grouped = Dictionary(grouping: declarations) { $0.contextPath ?? "" }

        for context in grouped.keys.sorted() {
            let members = grouped[context]!.sorted { $0.identity < $1.identity }
            let rendered = try members.map { try render($0, generation: generation) }

            if context.isEmpty {
                lines.append(contentsOf: rendered)
            } else {
                lines.append("extension \(context) {")
                lines.append(contentsOf: rendered.map { indent($0) })
                lines.append("}")
            }
            lines.append("")
        }

        return lines.joined(separator: "\n")
    }

    private static func render(_ declaration: PatchableDeclaration, generation: UInt64) throws -> String {
        let newName = "splice_g\(generation)_" + sanitise(declaration.identity)
        let attribute = "@_dynamicReplacement(for: \(declaration.replacementTarget))"

        if var function = declaration.node.as(FunctionDeclSyntax.self) {
            function.name = .identifier(newName)
            function.attributes = strip(function.attributes)
            function.modifiers = strip(function.modifiers)
            return attribute + "\n" + function.trimmedDescription
        }

        if var variable = declaration.node.as(VariableDeclSyntax.self),
           let binding = variable.bindings.first {
            variable.bindings = PatternBindingListSyntax([
                binding.with(\.pattern, PatternSyntax(IdentifierPatternSyntax(identifier: .identifier(newName))))
            ])
            variable.attributes = strip(variable.attributes)
            variable.modifiers = strip(variable.modifiers)
            return attribute + "\n" + variable.trimmedDescription
        }

        throw SpliceError(stage: .generate, subject: declaration.identity,
                          reason: "this generator only emits functions and computed properties",
                          recovery: .rebuild)
    }

    /// `final` is implied inside an extension and illegal on a struct member;
    /// everything else the original carried is load-bearing.
    private static func strip(_ modifiers: DeclModifierListSyntax) -> DeclModifierListSyntax {
        DeclModifierListSyntax(modifiers.filter { $0.name.tokenKind != .keyword(.final) })
    }

    private static func strip(_ attributes: AttributeListSyntax) -> AttributeListSyntax {
        AttributeListSyntax(attributes.filter { element in
            guard case .attribute(let attribute) = element else { return true }
            return attribute.attributeName.trimmedDescription != "_dynamicReplacement"
        })
    }

    private static func sanitise(_ identity: String) -> String {
        String(identity.map { $0.isLetter || $0.isNumber ? $0 : "_" })
    }

    private static func indent(_ block: String) -> String {
        block.split(separator: "\n", omittingEmptySubsequences: false)
            .map { $0.isEmpty ? "" : "    " + $0 }
            .joined(separator: "\n")
    }
}
